### ISSUE TITLE
Date format in Excel and done message

### ISSUE THREAD

**Issue by Saquibadil** [jitbit/CsvExport#11]
Hello,
Thank you for the wonderful class.

I have two issues 
1.  I am doing this to format date 
CsvExport.MakeValueCsvFriendly(new DateTime(year, mon, day, hour, min, 0));
But I see ##### in excel file

2. The preparingMessageHtml does not disappear or change after the file is downloaded.

Thank you!

**Comment by 0x-a6** [comment]
Check column width in excel for date.
