### ISSUE TITLE
Warning message in CSV

### ISSUE THREAD

**Issue by Saquibadil** [jitbit/CsvExport#13]
After downloading the CSV, I am getting this error message

![image](https://cloud.githubusercontent.com/assets/11774493/23781514/d3f0ba22-051b-11e7-9fc5-007815a6b057.png)

Some features in your workbook might be lost if you save it as CSV (Comma delimited).

Any ideas?

Thank you!

**Comment by jitbit** [comment]
That's MS Excel feature
