### ISSUE TITLE
sep=

### ISSUE THREAD

**Issue by jetstudio** [jitbit/CsvExport#14]
Hi,

Just tried using the CsvExport, how do I remove the first row "sep=" thing?

**Comment by jetstudio** [comment]
after reading the source code, I figured out to pass in "false" to CsvExort constructor to get rid of the "sep=" 

Please let me know if im doing this correctly, so that I can close this issue. Thanks.

**Comment by jitbit** [comment]
Yes, correct, just like described in the parameter tooltip
