### ISSUE TITLE
Error special characters

### ISSUE THREAD

**Issue by SD30190** [jitbit/CsvExport#17]
Hi guys,

I try to export csv file. I use functions "ExportToFile()" or "return File(myExport.ExportToBytes(), "text/csv", "results.csv"); ", these all cant convert UTF-8 and I get this 
![image](https://user-images.githubusercontent.com/17079066/37196775-abea0354-23aa-11e8-992e-3ae338dbee88.png).

Any suggestion? Thanks all.

**Comment by JesperLindberg** [comment]
Go into the class CsvExport, in method "ExportToBytes" change from UTF8 to UTF32

**Comment by tiensy300190** [comment]
Thanks JesperLindberg but it do not work :).

**Comment by alex-jitbit** [comment]
@SD30190  What app is this screenshot from?
