### ISSUE TITLE
New method

### ISSUE THREAD

**Issue by ezelargo** [jitbit/CsvExport#2]
Hi, how are you? thanks for this functionality.
Here i detail a method that expand the functionality in this class for use with generic lists

/// <summary>
        /// Add list of rows
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="list"></param>
        public void AddRows<T>(IEnumerable<T> list) where T : class {
            if (list.Any()) {
                foreach (var obj in list) {
                    AddRow();
                    var values = obj.GetType().GetProperties();
                    foreach (var value in values) {
                        this[value.Name] = value.GetValue(obj, null);
                    }
                }
            }
        }

**Comment by jitbit** [comment]
Yeah, I don't see why not... Will add this right away
