### ISSUE TITLE
The class opens the employing application to a formula injection vulnerability

### ISSUE THREAD

**Issue by interDist** [jitbit/CsvExport#23]
The function `MakeValueCsvFriendly` does not perform sufficient sanitisation of the exported values (specifically, it does not account for an equals sign ‘=’, a plus sign ‘+’ or a minus sign ‘-’ in the beginning of the value). Therefore, a value with a payload will result in a malicious formula injected into the CSV and executed when the file is opened by a spreadsheet software.
A developer who is insufficiently aware of such a vulnerability and makes use of the CsvExport class creates a security hole in their system.

Read more about the vulnerability here: https://owasp.org/www-community/attacks/CSV_Injection.

**Comment by alex-jitbit** [comment]
I don't think it's the exporter's job to sanitize content

https://en.wikipedia.org/wiki/Single-responsibility_principle

**Comment by interDist** [comment]
Well, at least add a warning to the README.
