### ISSUE TITLE
Missing arguments for MemoryStream.Write

### ISSUE THREAD

**Issue by dmenese** [jitbit/CsvExport#25]
Just downloaded your library, but it's not compiling -seems that is expecting a couple of parameters for MemoryStream.Write that you are not passing:
![image](https://user-images.githubusercontent.com/74675395/197452227-875eb2c0-3615-45f4-bcef-358c3516d189.png)

**Comment by dmenese** [comment]
Trying this change:
ms.Write(Encoding.UTF8.GetPreamble(), 0, Encoding.UTF8.GetPreamble().Length);

**Comment by alex-jitbit** [comment]
Compiles fine under .NET 5 and  .NET 6 for me, are you using .NET Framework?

**Comment by dmenese** [comment]
Correct. Didn't realize about that. Anyway, with that minor change it also works on .Net Framework.

**Comment by alex-jitbit** [comment]
We should probably move on from publishing a source file to a fully compiled NetStandard-compatible nuget package. We'll get to this shortly
